"""
HogShade: the generators: a host's material UI and the docs reference, produced from the material-type files
and a per-host map of names.
Package: hogshade/material/generators

``generate("maya_dx11")`` is the material block of ``hosts/maya_dx11/hogshade.fx`` between its two marker
lines; ``generate("docs")`` the Markdown reference of every type. The host map carries only what the schema
does not know (identifiers, labels, orders, groups); a value the schema knows is a finding in the map. The
S2 spec (Docs/superpowers/specs/s2-material-generators.md) fixes both outputs. Named ``generators``, not
``generate``: the package exports ``generate`` (failure-modes entry 13).
"""

from __future__ import annotations

import copy
import logging as _logging
import re
from functools import cache
from importlib import resources
from importlib.resources.abc import Traversable
from typing import Any

from hogshade.material.model import Finding, MaterialError, ParameterDef
from hogshade.material.schema import read_json, type_of, types

_MODULE_NAME = "hogshade.material.generators"
__version__ = "0.1.0"
__updated__ = "2026-10-01"
_LOGGER = _logging.getLogger(_MODULE_NAME)

#: The types whose union the Maya shell declares (the shell is one effect with a model selector).
MAYA_TYPES = ("hogshade-legacy-v2", "hogshade-legacy-v1")
#: The schema fields a shared parameter must agree on across types for one host-map entry to serve both.
EMISSION_FIELDS = ("type", "default", "range", "choices", "colour_space")
MAYA_BEGIN = "// BEGIN hogshade.material generated (tools/generate_material_ui.py --write); do not edit"
MAYA_END = "// END hogshade.material generated"
DOCS_HEADER = "<!-- generated by tools/generate_material_ui.py --write from hogshade/material/schema; do not edit -->"
MAYA_COLOUR_SPACES = {"srgb": "sRGB", "raw": "Raw"}
MAYA_SEMANTICS = ("OPACITY",)
_HOST_SUFFIX = ".json"
_ENTRY_KEYS = ("name", "label", "group", "order", "semantic", "map", "components", "component_choices")
_SCHEMA_KEYS = ("type", "default", "range", "choices", "colour_space", "doc", "soft", "widget", "strength")
_MAP_KEYS = ("name", "flag", "label", "order")
_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
#: HLSL words a parameter cannot be named; the shell would not compile.
HLSL_RESERVED = frozenset(
    [
        "bool",
        "int",
        "uint",
        "half",
        "float",
        "double",
        "float2",
        "float3",
        "float4",
        "int2",
        "int3",
        "int4",
        "uint2",
        "uint3",
        "uint4",
        "string",
        "struct",
        "technique",
        "pass",
        "sampler",
        "SamplerState",
        "Texture2D",
        "TextureCube",
        "Buffer",
        "cbuffer",
        "tbuffer",
        "const",
        "static",
        "shared",
        "uniform",
        "volatile",
        "extern",
        "if",
        "else",
        "for",
        "while",
        "do",
        "switch",
        "case",
        "default",
        "break",
        "continue",
        "return",
        "discard",
        "in",
        "out",
        "inout",
        "void",
        "true",
        "false",
        "register",
        "matrix",
        "vector",
        "texture",
        "typedef",
        "namespace",
        "class",
        "interface",
        "this",
    ]
)
_MARKER_LINE = r"^{marker}\r?$"


def _ident_ok(value: Any) -> bool:
    """An HLSL identifier that is not a reserved word."""
    return isinstance(value, str) and bool(_IDENT.match(value)) and value not in HLSL_RESERVED


def _label_ok(value: Any) -> bool:
    """A UI label the annotation string can carry: non-empty, no quote, no angle bracket."""
    return isinstance(value, str) and bool(value) and not any(ch in value for ch in '"<>\\')


_RULE = "// " + "-" * 85 + " "


def _hosts_dir() -> Traversable:
    return resources.files("hogshade.material") / "hosts"


def hosts() -> list[str]:
    """The shipped host maps' names."""
    return sorted(p.name[: -len(_HOST_SUFFIX)] for p in _hosts_dir().iterdir() if p.name.endswith(_HOST_SUFFIX))


@cache
def _host_map_cached(host: str) -> dict[str, Any]:
    shipped = hosts()
    if host not in shipped:
        raise MaterialError(f"no host map for {host!r}; shipped: {shipped}")
    return read_json(_hosts_dir() / f"{host}{_HOST_SUFFIX}", "host map")


def host_map(host: str) -> dict[str, Any]:
    """The shipped map of ``host``, parsed once and handed out as a copy; ``MaterialError`` when there is none."""
    return copy.deepcopy(_host_map_cached(host))


def _agree(a: ParameterDef, b: ParameterDef) -> bool:
    return all(getattr(a, f) == getattr(b, f) for f in EMISSION_FIELDS)


def union_of(type_names: tuple[str, ...] = MAYA_TYPES) -> dict[str, ParameterDef]:
    """
    The parameters of several types as one dictionary, in first-seen order. A parameter two types share
    must agree on the fields the emission reads (``EMISSION_FIELDS``); ``doc`` and ``strength`` may differ.
    """
    out: dict[str, ParameterDef] = {}
    for name in type_names:
        for pname, p in type_of(name).parameters.items():
            if pname in out and not _agree(out[pname], p):
                raise MaterialError(f"{pname!r} differs between {type_names} on a field the emission reads")
            out.setdefault(pname, p)
    return out


def _is_int(x: Any) -> bool:
    return isinstance(x, int) and not isinstance(x, bool)


def _check_map_entry(where: str, pname: str, m: Any, orders: dict[int, str], names: dict[str, str]) -> list[Finding]:
    out: list[Finding] = []
    if not isinstance(m, dict):
        return [Finding(where, pname, "map is an object with name, flag, label, order")]
    for key in _MAP_KEYS:
        if key not in m:
            out.append(Finding(where, pname, f"map is missing {key!r}"))
    for key in m:
        if key not in _MAP_KEYS:
            out.append(Finding(where, pname, f"map has an unknown key {key!r}"))
    for key in ("name", "flag"):
        ident = m.get(key)
        if not _ident_ok(ident):
            out.append(Finding(where, pname, f"map {key} is an identifier and not an HLSL word, got {ident!r}"))
        elif ident in names:
            out.append(Finding(where, pname, f"map {key} {ident!r} is already used by {names[ident]!r}"))
        else:
            names[ident] = pname
    if not _label_ok(m.get("label")):
        out.append(Finding(where, pname, "map label is a string without quotes or angle brackets"))
    order = m.get("order")
    if not _is_int(order):
        out.append(Finding(where, pname, "map order is an integer"))
    else:
        for o in (order, order + 1):  # the use flag takes order + 1
            if o in orders:
                out.append(Finding(where, pname, f"map order {o} is already used by {orders[o]!r}"))
            orders[o] = pname
    return out


def _check_component(where: str, pname: str, c: Any, orders: dict[int, str], names: dict[str, str]) -> list[Finding]:
    out: list[Finding] = []
    if not isinstance(c, dict) or set(c) != {"name", "label", "order"}:
        return [Finding(where, pname, "a component is an object with name, label, order")]
    if not _ident_ok(c["name"]):
        out.append(Finding(where, pname, f"component name is an identifier and not an HLSL word, got {c['name']!r}"))
    elif c["name"] in names:
        out.append(Finding(where, pname, f"component name {c['name']!r} is already used by {names[c['name']]!r}"))
    else:
        names[c["name"]] = pname
    if not _label_ok(c["label"]):
        out.append(Finding(where, pname, "component label is a string without quotes or angle brackets"))
    if not _is_int(c["order"]):
        out.append(Finding(where, pname, "component order is an integer"))
    elif c["order"] in orders:
        out.append(Finding(where, pname, f"component order {c['order']} is already used by {orders[c['order']]!r}"))
    else:
        orders[c["order"]] = pname
    return out


def _check_entry(
    where: str,
    pname: str,
    p: ParameterDef,
    e: Any,
    groups: dict[str, int],
    orders: dict[int, str],
    names: dict[str, str],
) -> list[Finding]:
    if not isinstance(e, dict):
        return [Finding(where, pname, "an entry is an object")]
    out: list[Finding] = []
    for key in e:
        if key in _SCHEMA_KEYS:
            out.append(Finding(where, pname, f"{key!r} repeats what the schema knows; the map carries names only"))
        elif key not in _ENTRY_KEYS:
            out.append(Finding(where, pname, f"unknown key {key!r}"))
    if p.texturable:
        if "map" not in e:
            out.append(Finding(where, pname, "a texturable parameter carries map"))
        else:
            out.extend(_check_map_entry(where, pname, e["map"], orders, names))
    elif "map" in e:
        out.append(Finding(where, pname, "map on a parameter the schema does not let a texture bind to"))
    if p.type == "texture":
        extra = set(e) - {"map"}
        if extra:
            out.append(Finding(where, pname, f"a texture parameter carries only map, not {sorted(extra)}"))
        return out
    if p.type == "vector3":
        comps = e.get("components")
        if not isinstance(comps, list) or len(comps) != 3:
            out.append(Finding(where, pname, "a vector3 carries three components"))
        else:
            for c in comps:
                out.extend(_check_component(where, pname, c, orders, names))
        choices = e.get("component_choices")
        if not isinstance(choices, str) or choices.count(":") != 1:
            out.append(Finding(where, pname, "component_choices is 'positive:negative'"))
        for key in ("name", "label", "order", "semantic"):
            if key in e:
                out.append(Finding(where, pname, f"a vector3 carries components, not {key!r}"))
    else:
        for key in ("name", "label", "order"):
            if key not in e:
                out.append(Finding(where, pname, f"missing {key!r}"))
        ident = e.get("name")
        if ident is not None:
            if not _ident_ok(ident):
                out.append(Finding(where, pname, f"name is an identifier and not an HLSL word, got {ident!r}"))
            elif ident in names:
                out.append(Finding(where, pname, f"name {ident!r} is already used by {names[ident]!r}"))
            else:
                names[ident] = pname
        if "label" in e and not _label_ok(e["label"]):
            out.append(Finding(where, pname, "label is a string without quotes or angle brackets"))
        order = e.get("order")
        if order is not None:
            if not _is_int(order):
                out.append(Finding(where, pname, "order is an integer"))
            elif order in orders:
                out.append(Finding(where, pname, f"order {order} is already used by {orders[order]!r}"))
            else:
                orders[order] = pname
        if "semantic" in e and e["semantic"] not in MAYA_SEMANTICS:
            out.append(Finding(where, pname, f"semantic is one of {MAYA_SEMANTICS}"))
        for key in ("components", "component_choices"):
            if key in e:
                out.append(Finding(where, pname, f"{key!r} is for a vector3"))
    if "group" not in e:
        out.append(Finding(where, pname, "missing 'group'"))
    elif e["group"] not in groups:
        out.append(Finding(where, pname, f"group {e['group']!r} is not one of the map's groups"))
    return out


TYPE_SUFFIX = "@"


def entries_for(hmap: dict[str, Any], type_name: str) -> dict[str, dict[str, Any]]:
    """
    The map's entries for one type, keyed by parameter name: a ``<parameter>@<type>`` key wins over the plain
    key for that type, and a plain entry whose ``types`` excludes the type is left out.
    """
    out: dict[str, dict[str, Any]] = {}
    params = type_of(type_name).parameters
    for key, entry in hmap["parameters"].items():
        pname, _, only = key.partition(TYPE_SUFFIX)
        if pname not in params or not isinstance(entry, dict):
            continue
        if only:
            if only == type_name:
                out[pname] = entry
        elif pname not in out and type_name in entry.get("types", [type_name]):
            out[pname] = entry
    return out


def _check_wgpu_entry(
    where: str,
    key: str,
    pname: str,
    p: ParameterDef,
    e: Any,
    fields: dict[str, int],
    written: dict[tuple[str, int], str],
) -> list[Finding]:
    if not isinstance(e, dict):
        return [Finding(where, key, "an entry is an object")]
    out: list[Finding] = []
    for k in e:
        if k in _SCHEMA_KEYS:
            out.append(
                Finding(where, key, f"{k!r} repeats what the schema knows; the map carries the frame layout only")
            )
        elif k not in ("field", "components", "types", "unsupported"):
            out.append(Finding(where, key, f"unknown key {k!r}"))
    if "unsupported" in e:
        if not isinstance(e["unsupported"], str) or not e["unsupported"]:
            out.append(Finding(where, key, "unsupported carries a reason"))
        if "field" in e or "components" in e:
            out.append(Finding(where, key, "a parameter is bound or unsupported, not both"))
        return out
    if p.type == "texture":
        return out + [Finding(where, key, "a texture parameter is unsupported in the wgpu host (no texture bindings)")]
    field, comps = e.get("field"), e.get("components")
    if field not in fields:
        return out + [Finding(where, key, f"field {field!r} is not one of the map's fields")]
    width = 3 if p.type in ("color3", "vector3") else 1
    if not (isinstance(comps, list) and len(comps) == width and all(_is_int(c) for c in comps)):
        return out + [Finding(where, key, f"a {p.type} writes {width} component(s) as integers")]
    for c in comps:
        if not 0 <= c < fields[field]:
            out.append(Finding(where, key, f"component {c} is outside {field!r} (width {fields[field]})"))
        elif (field, c) in written:
            out.append(Finding(where, key, f"{field}[{c}] is already written by {written[(field, c)]!r}"))
        else:
            written[(field, c)] = key
    if "types" in e and not (
        isinstance(e["types"], list) and e["types"] and all(isinstance(t, str) for t in e["types"])
    ):
        out.append(Finding(where, key, "types is a non-empty list of type names"))
    return out


def _check_wgpu_map(hmap: dict[str, Any], params: dict[str, ParameterDef], where: str) -> list[Finding]:
    out: list[Finding] = []
    for key in ("types", "fields"):
        if key not in hmap:
            out.append(Finding(where, "", f"missing top-level field {key!r}"))
    if out:
        return out
    type_names = hmap["types"]
    if not (isinstance(type_names, list) and type_names and all(t in types() for t in type_names)):
        return [Finding(where, "", f"types names shipped types; got {type_names!r}")]
    if len(set(type_names)) != len(type_names):
        return [Finding(where, "", f"types lists a type twice: {type_names!r}")]
    fields = hmap["fields"]
    if not (isinstance(fields, dict) and fields and all(_is_int(w) and w > 0 for w in fields.values())):
        return [Finding(where, "", "fields is an object of frame field name to its width")]
    entries = hmap["parameters"]
    if not isinstance(entries, dict):
        return [Finding(where, "", "parameters is an object keyed by parameter name, optionally @type")]
    for key, e in entries.items():
        pname, _, only = key.partition(TYPE_SUFFIX)
        if pname not in params:
            out.append(Finding(where, key, "not a parameter of the types this host carries"))
        elif only and (only not in type_names or pname not in type_of(only).parameters):
            out.append(Finding(where, key, f"the suffix names a type that does not carry {pname!r}"))
        if isinstance(e, dict) and isinstance(e.get("types"), list):
            for t in e["types"]:
                if t not in type_names:
                    out.append(Finding(where, key, f"types names {t!r}, which this host does not carry"))
    for tname in type_names:
        covered = entries_for(hmap, tname)
        for pname in type_of(tname).parameters:
            if pname not in covered:
                out.append(Finding(where, pname, f"no entry for {tname}"))
            # a plain entry that admits this type and a suffixed entry for it would both select it
            plain = entries.get(pname)
            if (
                f"{pname}{TYPE_SUFFIX}{tname}" in entries
                and isinstance(plain, dict)
                and tname in plain.get("types", [tname])
            ):
                out.append(
                    Finding(where, pname, f"two entries select it for {tname}: the plain one and the suffixed one")
                )
        written: dict[tuple[str, int], str] = {}
        for pname, e in covered.items():
            key = pname if pname in entries and entries[pname] is e else f"{pname}{TYPE_SUFFIX}{tname}"
            out.extend(_check_wgpu_entry(where, key, pname, type_of(tname).parameters[pname], e, fields, written))
    # one finding per entry, not per type that shares it
    seen: set[tuple[str, str]] = set()
    unique: list[Finding] = []
    for f in out:
        if (f.parameter, f.message) not in seen:
            seen.add((f.parameter, f.message))
            unique.append(f)
    return unique


def check_host_map(hmap: dict[str, Any], params: dict[str, ParameterDef], where: str = "<host map>") -> list[Finding]:
    """
    The host-map rules against the parameters it must cover; empty when it is complete. The map's ``host``
    picks the entry shape: the Maya UI shape (S2) or the wgpu frame shape (S3).
    """
    if not isinstance(hmap, dict):
        return [Finding(where, "", "a host map is a JSON object")]
    out: list[Finding] = []
    for key in ("host", "version", "parameters"):
        if key not in hmap:
            out.append(Finding(where, "", f"missing top-level field {key!r}"))
    if out:
        return out
    if not (_is_int(hmap["version"]) and hmap["version"] >= 1):
        out.append(Finding(where, "", "version is an integer from 1"))
    if hmap["host"] == "wgpu":
        return out + _check_wgpu_map(hmap, params, where)
    if "groups" not in hmap:
        return out + [Finding(where, "", "missing top-level field 'groups'")]
    groups = hmap["groups"]
    if not (isinstance(groups, dict) and groups and all(isinstance(g, str) and _is_int(o) for g, o in groups.items())):
        out.append(Finding(where, "", "groups is an object of group name to its leading order"))
        groups = {}
    entries = hmap["parameters"]
    if not isinstance(entries, dict):
        return out + [Finding(where, "", "parameters is an object keyed by schema parameter name")]
    for pname in entries:
        if pname not in params:
            out.append(Finding(where, pname, "not a parameter of the types this host declares"))
    for pname in params:
        if pname not in entries:
            out.append(Finding(where, pname, "no host-map entry"))
    orders: dict[int, str] = {}
    names: dict[str, str] = {}
    for pname, e in entries.items():
        if pname in params:
            out.extend(_check_entry(where, pname, params[pname], e, groups, orders, names))
    return out


# ------------------------------------------------------------------------------------------------- Maya


def _num(v: Any) -> str:
    if _is_int(v):
        return str(v)
    return repr(float(v))


def _annotation(group: str, label: str, order: int, *extra: str) -> str:
    parts = [f'string UIGroup = "{group}";', f'string UIName = "{label}";', *extra, f"int UIOrder = {order};"]
    return "< " + " ".join(parts) + " >"


def _maya_declaration(p: ParameterDef, e: dict[str, Any]) -> list[str]:
    group, label, order, name = e["group"], e["label"], e["order"], e["name"]
    sem = f" : {e['semantic']}" if "semantic" in e else ""
    if p.type == "color3":
        rgb = ", ".join(_num(v) for v in p.default)
        colour = 'string UIWidget = "Color";'
        return [f"float3 {name} {_annotation(group, label, order, colour)} = {{ {rgb} }};"]
    if p.type in ("float", "int"):
        lo, hi = p.range if p.range is not None else (0.0, 1.0)
        step = "1" if p.type == "int" else "0.001"
        lo_s, hi_s = (str(int(lo)), str(int(hi))) if p.type == "int" else (_num(lo), _num(hi))
        ann = _annotation(
            group,
            label,
            order,
            'string UIWidget = "Slider";',
            f"float UIMin = {lo_s};",
            f"float UIMax = {hi_s};",
            f"float UIStep = {step};",
        )
        return [f"{p.type} {name}{sem} {ann} = {_num(p.default)};"]
    if p.type == "bool":
        return [f"bool {name} {_annotation(group, label, order)} = {'true' if p.default else 'false'};"]
    if p.type == "enum":
        fields = ":".join(p.choices)
        ann = _annotation(group, label, order, f'string UIFieldNames = "{fields}";')
        return [f"int {name} {ann} = {list(p.choices).index(p.default)};"]
    raise MaterialError(f"{p.name}: no Maya declaration for type {p.type!r}")


def _maya_components(p: ParameterDef, e: dict[str, Any]) -> list[str]:
    lines = []
    for c, default in zip(e["components"], p.default):
        ann = _annotation(e["group"], c["label"], c["order"], f'string UIFieldNames = "{e["component_choices"]}";')
        lines.append(f"int {c['name']} {ann} = {0 if default > 0 else 1};")
    return lines


def _maya_map(p: ParameterDef, m: dict[str, Any]) -> list[str]:
    space = MAYA_COLOUR_SPACES[p.colour_space or "raw"]
    return [
        f"Texture2D {m['name']}",
        "<",
        f'    string UIGroup = "Material Maps"; string UIName = "{m["label"]}"; string ResourceType = "2D";',
        (
            f'    string ResourceName = ""; int mipmaplevels = 0; int UIOrder = {m["order"]}; '
            f'string ColorSpace = "{space}";'
        ),
        ">;",
        f"bool {m['flag']}",
        "<",
        f'    string UIGroup = "Material Maps"; string UIName = "Use {m["label"]}"; int UIOrder = {m["order"] + 1};',
        "> = false;",
    ]


def maya_block(hmap: dict[str, Any], params: dict[str, ParameterDef]) -> str:
    """The text between the shell's markers: the maps, then each group in the map's group order."""
    where = hmap.get("host", "<host map>") if isinstance(hmap, dict) else "<host map>"
    findings = check_host_map(hmap, params, where)
    if findings:
        raise MaterialError("malformed host map: " + "; ".join(str(f) for f in findings))
    entries = hmap["parameters"]
    lines: list[str] = [_RULE + "material maps (generated)", ""]
    maps = sorted(((e["map"], params[n]) for n, e in entries.items() if "map" in e), key=lambda t: t[0]["order"])
    for m, p in maps:
        lines.extend(_maya_map(p, m))
    for group, _ in sorted(hmap["groups"].items(), key=lambda t: t[1]):
        rows: list[tuple[int, list[str]]] = []
        for pname, e in entries.items():
            p = params[pname]
            if p.type == "texture" or e.get("group") != group:
                continue
            if p.type == "vector3":
                rows.append((min(c["order"] for c in e["components"]), _maya_components(p, e)))
            else:
                rows.append((e["order"], _maya_declaration(p, e)))
        if not rows:
            continue
        lines.extend(["", _RULE + f"{group} (generated)", ""])
        for _, decl in sorted(rows, key=lambda t: t[0]):
            lines.extend(decl)
    return "\n".join(lines) + "\n"


def _span(text: str, begin: str, end: str, what: str) -> tuple[int, int]:
    """
    The start of the line after the ``begin`` marker and the start of the ``end`` marker line; each marker
    is a whole line (CRLF tolerated), present exactly once, in order. ``MaterialError`` otherwise.
    """
    begins = list(re.finditer(_MARKER_LINE.format(marker=re.escape(begin)), text, re.MULTILINE))
    ends = list(re.finditer(_MARKER_LINE.format(marker=re.escape(end)), text, re.MULTILINE))
    if len(begins) != 1 or len(ends) != 1:
        raise MaterialError(
            f"{what}: the markers {begin!r} and {end!r} must each appear exactly once as a line "
            f"(found {len(begins)} and {len(ends)})"
        )
    i, j = begins[0].end() + 1, ends[0].start()
    if j < i:
        raise MaterialError(f"{what}: the END marker precedes the BEGIN marker")
    return i, j


def replace_between(text: str, begin: str, end: str, body: str, what: str) -> str:
    """``text`` with the lines between the ``begin`` and ``end`` marker lines replaced by ``body``."""
    i, j = _span(text, begin, end, what)
    return text[:i] + body + text[j:]


def between(text: str, begin: str, end: str, what: str) -> str:
    """The text between the marker lines, as ``replace_between`` would replace it."""
    i, j = _span(text, begin, end, what)
    return text[i:j]


# ------------------------------------------------------------------------------------------------- docs


def _cell(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_cell(x) for x in v) + "]"
    return str(v).replace("|", "\\|")


def docs_reference(type_names: list[str] | None = None) -> str:
    """The Markdown reference of the shipped types: a table per type, parameters in file order."""
    names = list(type_names) if type_names is not None else types()
    out = [
        DOCS_HEADER,
        "# Material types, the reference",
        "",
        "**Status:** Living. Generated from `hogshade/material/schema/*.material-type.json` by",
        "`tools/generate_material_ui.py --write`; edit the schema, not this file.",
        "",
    ]
    for name in names:
        mtype = type_of(name)
        out += [f"## `{name}` (version {mtype.version})", "", mtype.title + ".", ""]
        out.append("Groups: " + ", ".join(f"`{g}`" for g in mtype.groups) + ".")
        if mtype.optional_groups:
            out.append("Opt-in groups: " + ", ".join(f"`{g}`" for g in mtype.optional_groups) + ".")
        out += [
            "",
            (
                "| Parameter | Type | Default | Range | Group | Widget | Semantic | Colour space | Overridable | Tier "
                "| Doc |"
            ),
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for p in mtype.parameters.values():
            rng = _cell(list(p.range)) + (" soft" if p.soft else "") if p.range is not None else ""
            default = _cell(p.default) if p.type != "enum" else f"`{p.default}` of {_cell(list(p.choices))}"
            out.append(
                f"| `{p.name}` | {p.type} | {default} | {rng} | {p.group} | {p.widget} | {p.semantic} | "
                f"{_cell(p.colour_space)} | {_cell(p.overridable)} | {_cell(p.tier)} | {_cell(p.doc)} |"
            )
        out.append("")
    return "\n".join(out)


# ------------------------------------------------------------------------------------------------- entry


def generate(host: str, *, types: list[str] | None = None) -> str:
    """
    One host's text: ``"maya_dx11"`` the shell's material block (always the legacy union), ``"docs"`` the
    reference (``types`` restricts it). An unknown host is ``MaterialError``.
    """
    if host == "docs":
        return docs_reference(types)
    if host == "maya_dx11":
        return maya_block(host_map(host), union_of(MAYA_TYPES))
    raise MaterialError(f"no generator for host {host!r}; one of ['docs', 'maya_dx11']")


if __name__ == "__main__":
    # smoke run: print the Maya block
    print(generate("maya_dx11"))
