"""
HogShade: the library of materials: the documents under a root, in roster order, and the generated index page.
Package: hogshade/material/library

The documents live under ``content/materials/``, outside the package, so every function here takes the root
directory. ``documents_under`` lists them parents first within a family; ``index`` loads, validates and
resolves each one and renders the Markdown index (a table per family, the deferred list, the reverse table's
losses), refusing a library with a finding so the page cannot describe a broken set. The S4a spec
(Docs/superpowers/specs/s4a-material-library.md) fixes the shape. Standard library only.
"""

from __future__ import annotations

import logging as _logging
from pathlib import Path

from hogshade.material.conversion import load_table
from hogshade.material.document import load
from hogshade.material.model import Document, MaterialError
from hogshade.material.resolution import resolve
from hogshade.material.schema import type_of
from hogshade.material.validation import validate

_MODULE_NAME = "hogshade.material.library"
__version__ = "0.1.0"
__updated__ = "2026-10-03"
_LOGGER = _logging.getLogger(_MODULE_NAME)

PARENT_NAME = "base.material.json"
SUFFIX = ".material.json"
INDEX_HEADER = (
    "<!-- generated by tools/generate_material_ui.py --write from content/materials/standard; do not edit -->"
)
#: The families in the order the index and the contact sheet show them.
FAMILY_ORDER = ("metal", "dielectric", "coated", "rough", "emissive", "cutout")
#: Materials the standard's version 1 cannot carry honestly, named rather than faked.
DEFERRED = (
    ("skin", "subsurface scattering; no subsurface layer in the standard's version 1"),
    ("cloth with sheen", "no sheen lobe in the standard's version 1"),
    ("glass and water", "no transmission in the standard's version 1"),
    ("car paint with a true coat", "no coat layer in the standard's version 1; the coated family approximates it"),
)
#: What the reverse table cannot say: a loss the entry shape has no place for.
UNSTATED_LOSSES = (
    (
        "geometry_normal strength",
        (
            "does not reach bump_intensity: a table entry maps a parameter, not a field of one, and geometry_normal "
            "is already mapped to normal_map; a source-side field is S4b's conversion change"
        ),
    ),
)


def _family_rank(family: str) -> tuple[int, str]:
    return (FAMILY_ORDER.index(family) if family in FAMILY_ORDER else len(FAMILY_ORDER), family)


def documents_under(root: str | Path) -> list[Path]:
    """
    Every ``*.material.json`` under ``root``: families in ``FAMILY_ORDER`` then alphabetical, the family's
    parent (``base.material.json``) first, children alphabetical. A document directly under ``root`` sorts
    before the families, under the family name ``""``.
    """
    root = Path(root)
    if not root.is_dir():
        raise MaterialError(f"no such library root: {root}")

    def key(p: Path) -> tuple[tuple[int, str], int, str]:
        family = p.parent.relative_to(root).as_posix() if p.parent != root else ""
        return (_family_rank(family), 0 if p.name == PARENT_NAME else 1, p.name)

    return sorted((p for p in root.rglob(f"*{SUFFIX}") if p.is_file()), key=key)


def family_of(path: Path, root: Path) -> str:
    """The family a document belongs to: its directory relative to the root (``""`` at the root)."""
    rel = path.parent.relative_to(root)
    return rel.as_posix() if rel != Path() else ""


def _check(doc: Document, root: Path) -> list[str]:
    """Every finding of a document and its resolution, as strings; the family rule too."""
    problems = [str(f) for f in validate(doc)]
    if doc.parent is not None and doc.parent != PARENT_NAME:
        problems.append(f"{doc.path}: a child's parent is {PARENT_NAME!r} beside it, not {doc.parent!r}")
    if not problems:
        try:
            problems.extend(str(f) for f in validate(resolve(doc, root)))
        except MaterialError as e:
            problems.append(str(e))
    return problems


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _sets(doc: Document) -> str:
    return ", ".join(f"`{name}`" for name in doc.values) or "nothing (the parent's values)"


def _sources(doc: Document) -> str:
    return "; ".join(f"{_cell(p['source'])}: {_cell(p['note'])}" for p in doc.provenance) or "none"


def index(root: str | Path, table_to: str = "hogshade-legacy-v2") -> str:
    """
    The Markdown index of the library at ``root``. Loads, validates and resolves every document; a finding
    anywhere is ``MaterialError`` naming them all. ``table_to`` names the type whose reverse table's losses
    the page lists (the type the hosts render today).
    """
    root = Path(root).resolve()
    paths = documents_under(root)
    docs: list[tuple[str, Document]] = []
    problems: list[str] = []
    for p in paths:
        try:
            doc = load(p, root)
        except MaterialError as e:
            problems.append(str(e))
            continue
        problems.extend(_check(doc, root))
        docs.append((family_of(p, root), doc))
    if problems:
        raise MaterialError(f"the library at {root} has findings: " + "; ".join(problems))
    type_names = sorted({d.material_type for _, d in docs})
    _LOGGER.info(
        "indexed %d documents in %d families under %s (%s)", len(docs), len({f for f, _ in docs}), root, type_names
    )
    out = [
        INDEX_HEADER,
        "# The library of materials",
        "",
        "**Status:** Living. Generated from the documents under `content/materials/standard/` by",
        "`tools/generate_material_ui.py --write` and checked in CI; edit a document, not this page. Every",
        "constant carries its source in the document's `provenance`. The S4a spec says why each family exists.",
        "",
        f"{len(docs)} documents of type {', '.join(f'`{t}`' for t in type_names)}; a child's `parent` is",
        f"`{PARENT_NAME}` beside it (S1's path rule allows no `..`). The hosts render the set today through the",
        f"conversion table to `{table_to}`; what that loses is listed at the end.",
        "",
    ]
    for family in dict.fromkeys(f for f, _ in docs):
        members = [d for f, d in docs if f == family]
        out += [
            f"## `{family or '.'}`",
            "",
            "| Document | Title | What | Sets | Sources |",
            "| --- | --- | --- | --- | --- |",
        ]
        for d in members:
            name = d.path.name if d.path else "<memory>"
            role = "parent" if name == PARENT_NAME else "child"
            out.append(
                f"| `{name}` ({role}) | {_cell(d.title or '')} | {_cell(d.doc or '')} | {_sets(d)} | {_sources(d)} |"
            )
        out.append("")
    out += ["## Deferred, not faked", ""]
    out += [f"- **{name}**: {why}." for name, why in DEFERRED]
    out.append("")
    try:
        table = load_table(type_names[0], table_to) if len(type_names) == 1 else None
    except MaterialError:
        table = None
    if table is not None:
        out += [f"## What `{type_names[0]}` to `{table_to}` loses", ""]
        out += [f"- `{d['from']}`: {d['reason']}." for d in table["dropped"]]
        out += [f"- {name}: {why}." for name, why in UNSTATED_LOSSES]
        out.append("")
    return "\n".join(out)


def factor_parameters(type_name: str) -> list[str]:
    """The parameters of a type a document can set without a texture: everything but the texture type."""
    return [name for name, p in type_of(type_name).parameters.items() if p.type != "texture"]


def coverage(root: str | Path, type_name: str = "hogshade-standard") -> dict[str, list[str]]:
    """Factor-bearing parameter of ``type_name`` to the documents under ``root`` that set it (raw, not resolved)."""
    root = Path(root).resolve()
    out: dict[str, list[str]] = {name: [] for name in factor_parameters(type_name)}
    for p in documents_under(root):
        doc = load(p, root)
        if doc.material_type != type_name:
            continue
        for name in doc.values:
            if name in out:
                out[name].append(p.relative_to(root).as_posix())
    return out


if __name__ == "__main__":
    # smoke run: python -m hogshade.material.library <root>
    import sys

    _root = sys.argv[1] if len(sys.argv) > 1 else "content/materials/standard"
    print(index(_root))
    for _name, _docs in coverage(_root).items():
        print(_name, len(_docs))
