"""
HogShade: derive this repo's Job_Orchestrator (BATS) profile and worker environments from the orchestrator's canon.
Package: tools/bats/make_profile

    uv run tools/bats/make_profile.py     # writes orchestrator_config_hogshade.json and hogshade_*_env.json here

HogShade's workers are its own named types, the pattern the orchestrator uses for studio variants:

| Type | Pool | For |
| --- | --- | --- |
| `hogshade_maya` | one headless mayapy | cooks, scene builds, anything without a viewport |
| `hogshade_maya_gui` | one maya.exe, DirectX 11 viewport | dx11Shader checks, playblasts, captures |
| `hogshade_python` | one venv Python | the IBL cook and other NumPy jobs |
| `hogshade_blender` | one headless Blender 5.2 | the Blender host, bakes and the required comparison path |
| `marmoset` | a bridge to Marmoset Toolbag 4, a fresh Toolbag per job | the baked-maps tier of T4 |

`marmoset` is the one type that keeps the canon's name (the worker's RPC server and the orchestrator know it by that
name; the owner, 2026-10-05) and takes no environment file: its jobs run inside Toolbag's embedded Python 3.9, which
imports nothing from here, and the canon ships it inert (pool 0), so this profile only turns the pool to 1. A job
reaches Toolbag by writing files (a scene path in, files out); nothing is held between jobs.

Every worker carries an explicit environment file (`environment_json_path`), because the
orchestrator resolves profile-based environments by worker type name and a renamed type would boot
with no PYTHONPATH at all. A direct environment file gets no profile inheritance either, so each
generated file folds the canon base environment (the orchestrator's own package path and variables)
in itself, then the DCC's environment, then HogShade's additions: the HogShade root on PYTHONPATH
(MODULE-mode jobs import `hogshade.*`), `HOGSHADE_ROOT`, and for the GUI Maya the viewport override.
The profile keeps the canon's paths, scaling, GPU, monitoring and log settings verbatim so it follows
the dev orchestrator as it moves. Re-run after pulling Job_Orchestrator; the diff is the review.
JOB_ORCHESTRATOR_ROOT names the checkout (default D:/Depot/Job_Orchestrator).
"""

from __future__ import annotations

import json
import logging as _logging
import os
from pathlib import Path

_MODULE_NAME = "tools.bats.make_profile"
__version__ = "0.2.0"
__updated__ = "2026-10-05"
_LOGGER = _logging.getLogger(_MODULE_NAME)

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
JO_ROOT = Path(os.environ.get("JOB_ORCHESTRATOR_ROOT", "D:/Depot/Job_Orchestrator"))
CONFIG_DIR = JO_ROOT / "job_orchestrator" / "config"
CANON = CONFIG_DIR / "orchestrator_config.json"
BASE_ENV = CONFIG_DIR / "base_env.json"
PROFILE_OUT = HERE / "orchestrator_config_hogshade.json"

# worker type -> (canon worker type, canon environment file, generated environment file, extra variables)
WORKERS = {
    "hogshade_maya": ("maya", "maya_env.json", "hogshade_maya_env.json", {}),
    "hogshade_maya_gui": (
        "maya",
        "maya_env.json",
        "hogshade_maya_env.json",
        {"MAYA_VP2_DEVICE_OVERRIDE": "VirtualDeviceDx11"},
    ),
    "hogshade_python": ("python", "python_env.json", "hogshade_python_env.json", {}),
    "hogshade_blender": ("blender", "blender_env.json", "hogshade_blender_env.json", {}),
}


def _fwd(p: Path | str) -> str:
    return str(p).replace("\\", "/")


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _clone(d: dict) -> dict:
    return json.loads(json.dumps(d))


def build_env(base: dict, dcc: dict, name: str, extra: dict) -> dict:
    """Base environment first, the DCC's on top, HogShade's additions last; lists keep order, no duplicates."""
    out = {
        "name": f"HogShade {name} worker environment",
        "description": (
            f"Generated by tools/bats/make_profile.py from the canon base and {name} environments plus the "
            "HogShade root; the orchestrator applies no inheritance to a direct environment file, so the base "
            "is folded in here. Never hand-edited."
        ),
        "environment": {
            "variables": {},
            "PATH": {"prepend": [], "append": []},
            "PYTHONPATH": {"prepend": [], "append": []},
        },
    }
    env = out["environment"]
    for source in (base.get("environment", {}), dcc.get("environment", {})):
        env["variables"].update(source.get("variables", {}))
        for key in ("PATH", "PYTHONPATH"):
            for slot in ("prepend", "append"):
                for item in source.get(key, {}).get(slot, []):
                    if item not in env[key][slot]:
                        env[key][slot].append(item)
    env["variables"]["HOGSHADE_ROOT"] = _fwd(ROOT)
    env["variables"].update(extra)
    if _fwd(ROOT) not in env["PYTHONPATH"]["prepend"]:
        env["PYTHONPATH"]["prepend"].insert(0, _fwd(ROOT))
    return out


def build_profile(canon: dict) -> dict:
    # package_paths is the dev checkout's own sys.path additions; HogShade's workers need none of them
    profile = {k: v for k, v in canon.items() if k not in ("worker_types", "package_paths")}
    profile["_hogshade"] = {
        "generated_by": "tools/bats/make_profile.py",
        "from": _fwd(CANON),
        "note": (
            "HogShade development profile: canon settings, HogShade's own worker types. Regenerate, never hand-edit."
        ),
    }
    profile["dcc_paths"] = dict(canon["dcc_paths"])
    workers: dict = {}
    for name, (canon_type, _env_file, env_out, _extra) in WORKERS.items():
        w = _clone(canon["worker_types"][canon_type])
        w["environment_json_path"] = _fwd(HERE / env_out)
        w.pop("environment", None)
        # the environment manager expands ${<TYPE>_LOCATION} from dcc_paths keyed by the worker type name
        if canon_type in canon["dcc_paths"]:
            profile["dcc_paths"][name] = dict(canon["dcc_paths"][canon_type])
        workers[name] = w
    maya_paths = canon["dcc_paths"]["maya"]
    for name in ("hogshade_maya", "hogshade_maya_gui"):
        workers[name]["executable_paths"] = {
            "headless": _fwd(maya_paths["mayapy"]),
            "gui": _fwd(maya_paths["executable"]),
        }
    workers["hogshade_maya"]["display_name"] = "HogShade Maya (headless)"
    workers["hogshade_maya"]["description"] = (
        "HogShade: mayapy for cooks, scene builds and checks that need no viewport"
    )
    workers["hogshade_maya"]["pool_sizes"] = {"headless": 1, "gui": 0}
    workers["hogshade_maya_gui"]["display_name"] = "HogShade Maya (GUI, DirectX 11)"
    workers["hogshade_maya_gui"]["description"] = (
        "HogShade: maya.exe with the DirectX 11 viewport for dx11Shader checks, playblasts and captures"
    )
    workers["hogshade_maya_gui"]["pool_sizes"] = {"headless": 0, "gui": 1}
    workers["hogshade_python"]["display_name"] = "HogShade Python"
    workers["hogshade_python"]["description"] = "HogShade: the IBL cook and other NumPy jobs on the orchestrator venv"
    workers["hogshade_python"]["pool_sizes"] = {"headless": 1}
    blender_paths = canon["dcc_paths"]["blender"]
    workers["hogshade_blender"]["display_name"] = "HogShade Blender (headless)"
    workers["hogshade_blender"]["description"] = (
        "HogShade: Blender 5.2 in the background for the Blender host, bakes and the required comparison path"
    )
    workers["hogshade_blender"]["executable_paths"] = {"headless": _fwd(blender_paths["executable"])}
    workers["hogshade_blender"]["pool_sizes"] = {"headless": 1}
    if "marmoset" in canon["worker_types"]:  # the canon ships it inert; Toolbag 4 is installed on the dev machine
        workers["marmoset"] = _clone(canon["worker_types"]["marmoset"])
        workers["marmoset"]["pool_sizes"] = {"headless": 1}
        _LOGGER.info("marmoset worker type enabled with a pool of 1 (a fresh Toolbag per job)")
    profile["worker_types"] = workers
    return profile


def main() -> int:
    canon = _load(CANON)
    base = _load(BASE_ENV)
    written: list[str] = []
    for canon_type, env_file, env_out, extra in WORKERS.values():
        if env_out in written:
            continue
        # the two Maya types share one file; the GUI override applies to both (headless ignores it)
        extras = dict(extra)
        for _t, _f, other_out, other_extra in WORKERS.values():
            if other_out == env_out:
                extras.update(other_extra)
        env = build_env(base, _load(CONFIG_DIR / env_file), canon_type, extras)
        (HERE / env_out).write_text(json.dumps(env, indent=2) + "\n", encoding="utf-8")
        written.append(env_out)
    profile = build_profile(canon)
    PROFILE_OUT.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {PROFILE_OUT.name} and {written} from {CONFIG_DIR}: workers {list(profile['worker_types'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
