"""
HogShade: derive this repo's Job_Orchestrator (BATS) profile and worker environment from the orchestrator's canon.
Package: tools/bats/make_profile

    uv run tools/bats/make_profile.py     # writes orchestrator_config_hogshade.json and hogshade_maya_env.json here

HogShade's workers are its own named types, the pattern the orchestrator uses for studio variants:

| Type | Pool | For |
| --- | --- | --- |
| `hogshade_maya` | one headless mayapy | cooks, scene builds, anything without a viewport |
| `hogshade_maya_gui` | one maya.exe, DirectX 11 viewport | dx11Shader checks, playblasts, captures |
| `hogshade_python` | one venv Python | the IBL cook and other NumPy jobs |

Everything in HogShade that needs Maya runs through the two Maya types; a Blender pair joins the same
way when that host lands. Both Maya types share `hogshade_maya_env.json`, derived from the canon Maya
environment with the HogShade root on PYTHONPATH (so MODULE-mode jobs import `hogshade.*`) and the
viewport override. The profile keeps the canon's paths, scaling, GPU, monitoring and log settings
verbatim so it follows the dev orchestrator as it moves. Re-run after pulling Job_Orchestrator; the
diff is the review. JOB_ORCHESTRATOR_ROOT names the checkout (default D:/Depot/Job_Orchestrator).
"""

from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
JO_ROOT = Path(os.environ.get("JOB_ORCHESTRATOR_ROOT", "D:/Depot/Job_Orchestrator"))
CONFIG_DIR = JO_ROOT / "job_orchestrator" / "config"
CANON = CONFIG_DIR / "orchestrator_config.json"
MAYA_ENV = CONFIG_DIR / "maya_env.json"
PROFILE_OUT = HERE / "orchestrator_config_hogshade.json"
ENV_OUT = HERE / "hogshade_maya_env.json"


def _fwd(p: Path) -> str:
    return str(p).replace("\\", "/")


def build_maya_env(canon_env: dict) -> dict:
    env = json.loads(json.dumps(canon_env))
    env["name"] = "HogShade Maya 2026 worker environment"
    env["description"] = (
        "The canon Maya 2026 environment plus the HogShade root on PYTHONPATH and the DirectX 11 viewport "
        "override; generated by tools/bats/make_profile.py, never hand-edited"
    )
    variables = env["environment"].setdefault("variables", {})
    variables["MAYA_VP2_DEVICE_OVERRIDE"] = "VirtualDeviceDx11"
    variables["HOGSHADE_ROOT"] = _fwd(ROOT)
    pp = env["environment"].setdefault("PYTHONPATH", {"prepend": [], "append": []})
    root = _fwd(ROOT)
    if root not in pp["prepend"]:
        pp["prepend"].insert(0, root)
    return env


def build_profile(canon: dict) -> dict:
    profile = {k: v for k, v in canon.items() if k != "worker_types"}
    profile["_hogshade"] = {
        "generated_by": "tools/bats/make_profile.py",
        "from": _fwd(CANON),
        "note": "HogShade development profile: canon settings, HogShade's own worker types. Regenerate, never hand-edit.",
    }
    maya_paths = canon["dcc_paths"]["maya"]
    # the environment manager expands ${<TYPE>_LOCATION} from dcc_paths keyed by the worker type name
    profile["dcc_paths"] = dict(canon["dcc_paths"])
    profile["dcc_paths"]["hogshade_maya"] = dict(maya_paths)
    profile["dcc_paths"]["hogshade_maya_gui"] = dict(maya_paths)

    maya_template = json.loads(json.dumps(canon["worker_types"]["maya"]))
    maya_template["environment_json_path"] = _fwd(ENV_OUT)
    maya_template["executable_paths"] = {
        "headless": _fwd(Path(maya_paths["mayapy"])),
        "gui": _fwd(Path(maya_paths["executable"])),
    }

    headless = json.loads(json.dumps(maya_template))
    headless["display_name"] = "HogShade Maya (headless)"
    headless["description"] = "HogShade: mayapy for cooks, scene builds and checks that need no viewport"
    headless["pool_sizes"] = {"headless": 1, "gui": 0}

    gui = json.loads(json.dumps(maya_template))
    gui["display_name"] = "HogShade Maya (GUI, DirectX 11)"
    gui["description"] = (
        "HogShade: maya.exe with the DirectX 11 viewport for dx11Shader checks, playblasts and captures"
    )
    gui["pool_sizes"] = {"headless": 0, "gui": 1}

    python = json.loads(json.dumps(canon["worker_types"]["python"]))
    python["display_name"] = "HogShade Python"
    python["description"] = "HogShade: the IBL cook and other NumPy jobs on the orchestrator venv"
    python["pool_sizes"] = {"headless": 1}
    python["environment"] = dict(python.get("environment", {}))
    python["environment"]["HOGSHADE_ROOT"] = _fwd(ROOT)

    profile["worker_types"] = {"hogshade_maya": headless, "hogshade_maya_gui": gui, "hogshade_python": python}
    return profile


def main() -> int:
    canon = json.loads(CANON.read_text(encoding="utf-8"))
    ENV_OUT.write_text(
        json.dumps(build_maya_env(json.loads(MAYA_ENV.read_text(encoding="utf-8"))), indent=2) + "\n", encoding="utf-8"
    )
    profile = build_profile(canon)
    PROFILE_OUT.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {PROFILE_OUT.name} and {ENV_OUT.name} from {CONFIG_DIR}: workers {list(profile['worker_types'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
