"""
HogShade: stitch the WGSL core, validate it, translate it for the hosts, and compile what the hosts compile.
Package: tools/build_shaders.py

    uv run tools/build_shaders.py            # build everything, write hosts/*/generated/
    uv run tools/build_shaders.py --check    # build to a temp dir and fail if it differs from what is committed

Steps (Docs/specs/phase-2-restructure.md, "Toolchain"):
  1. read core/manifest.toml; concatenate the modules in order; enforce the naming rule
  2. naga validate the stitched core plus the validation entry point
  3. naga -> hosts/maya_dx11/generated/hogshade_core_sm5.hlsl   (shader model 5.0; fxc /T ps_5_0 compiles it)
     naga -> hosts/hlsl/hogshade_core.hlsl                       (shader model 6.0; dxc -T ps_6_0 compiles it)
     naga -> hosts/maya_ogsfx/generated/hogshade_core.frag       (GLSL core profile; naga picks the language from the .frag extension)
     copy -> hosts/wgpu/generated/hogshade_core.wgsl             (the core itself, the wgpu deliverable)
  4. fxc and dxc validation when those tools are on this machine (Windows SDK); skipped elsewhere
  5. write hosts/generated_manifest.json with the sha256 of every artifact

Every step's tool is optional at import time and mandatory when asked for: a missing naga is an
error for a build and a skip for a test that says so.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "core"
HOSTS = ROOT / "hosts"

ARTIFACTS = {
    "wgsl": HOSTS / "wgpu" / "generated" / "hogshade_core.wgsl",
    "hlsl_sm5": HOSTS / "maya_dx11" / "generated" / "hogshade_core_sm5.hlsl",
    "hlsl_sm6": HOSTS / "hlsl" / "hogshade_core.hlsl",
    "glsl": HOSTS / "maya_ogsfx" / "generated" / "hogshade_core.frag",
}

_DECL = re.compile(r"^\s*(?:fn|struct|const)\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)


class BuildError(RuntimeError):
    pass


def find_tool(name: str, extra_dirs: list[Path] | None = None) -> str | None:
    """Locate a tool on PATH, in the cargo bin, or in the Windows SDK bin folders."""
    found = shutil.which(name)
    if found:
        return found
    candidates = [Path.home() / ".cargo" / "bin" / f"{name}.exe"]
    sdk = Path(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")) / "Windows Kits" / "10" / "bin"
    if sdk.exists():
        for ver in sorted(sdk.glob("10.*"), reverse=True):
            candidates.append(ver / "x64" / f"{name}.exe")
    for extra in extra_dirs or []:
        candidates.append(extra / f"{name}.exe")
    for c in candidates:
        if c.exists():
            return str(c)
    return None


def load_manifest() -> dict:
    return tomllib.loads((CORE / "manifest.toml").read_text(encoding="utf-8"))


def check_names(manifest: dict, sources: list[tuple[str, str, str]]) -> None:
    """Every declared name carries its module prefix or is exempt; no name is declared twice."""
    exempt = set(manifest.get("names", {}).get("exempt", []))
    seen: dict[str, str] = {}
    problems: list[str] = []
    for file, prefix, text in sources:
        for name in _DECL.findall(text):
            if name in seen:
                problems.append(f"{file}: '{name}' already declared in {seen[name]}")
            seen[name] = file
            if name in exempt:
                continue
            if not name.startswith(prefix):
                # a model's entry points are <model>_inputs / <model>_evaluate_* which is exactly its prefix
                problems.append(f"{file}: '{name}' does not start with '{prefix}' and is not exempt")
    if problems:
        raise BuildError("naming rule violations:\n  " + "\n  ".join(problems))


def stitch(manifest: dict, with_validate: bool) -> str:
    sources = []
    for module in manifest["module"]:
        text = (CORE / module["file"]).read_text(encoding="utf-8")
        sources.append((module["file"], module["prefix"], text))
    check_names(manifest, sources)
    parts = [
        "// HogShade core, generated by tools/build_shaders.py from core/manifest.toml. Do not edit.\n"
        "// Modules, in order: " + ", ".join(m["file"] for m in manifest["module"]) + "\n",
    ]
    parts += [f"\n// ---- {file} ----\n{text}" for file, _, text in sources]
    if with_validate:
        vfile = manifest["validate"]["file"]
        parts.append(f"\n// ---- {vfile} (validation entry point, not part of the core) ----\n")
        parts.append((CORE / vfile).read_text(encoding="utf-8"))
    return "".join(parts)


def run(cmd: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise BuildError(f"{' '.join(cmd)}\n{proc.stdout}\n{proc.stderr}")
    return proc.stdout + proc.stderr


def build(out_dir: Path, require_compilers: bool = False) -> dict[str, str]:
    """Build every artifact under out_dir (mirroring hosts/); return {artifact: sha256}."""
    naga = find_tool("naga")
    if not naga:
        raise BuildError("naga not found: cargo install naga-cli (Docs/verification/toolchain.md)")
    manifest = load_manifest()
    entry = manifest["validate"]["entry_point"]
    core_only = stitch(manifest, with_validate=False)
    with_entry = stitch(manifest, with_validate=True)

    work = Path(tempfile.mkdtemp(prefix="hogshade_build_"))
    stitched = work / "hogshade_core_validate.wgsl"
    stitched.write_text(with_entry, encoding="utf-8", newline="\n")
    run([naga, str(stitched)])  # validation only

    targets = {
        "wgsl": out_dir / ARTIFACTS["wgsl"].relative_to(HOSTS),
        "hlsl_sm5": out_dir / ARTIFACTS["hlsl_sm5"].relative_to(HOSTS),
        "hlsl_sm6": out_dir / ARTIFACTS["hlsl_sm6"].relative_to(HOSTS),
        "glsl": out_dir / ARTIFACTS["glsl"].relative_to(HOSTS),
    }
    for p in targets.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    targets["wgsl"].write_text(core_only, encoding="utf-8", newline="\n")
    run([naga, "--shader-model", "50", str(stitched), str(targets["hlsl_sm5"])])
    run([naga, "--shader-model", "60", str(stitched), str(targets["hlsl_sm6"])])
    run(
        [
            naga,
            "--profile",
            "core",
            "--shader-stage",
            "frag",
            "--entry-point",
            entry,
            str(stitched),
            str(targets["glsl"]),
        ]
    )

    fxc = find_tool("fxc")
    dxc = find_tool("dxc")
    if fxc:
        run([fxc, "/nologo", "/T", "ps_5_0", "/E", entry, "/Fo", str(work / "sm5.cso"), str(targets["hlsl_sm5"])])
    elif require_compilers:
        raise BuildError("fxc not found (Windows 10 SDK)")
    if dxc:
        run([dxc, "-T", "ps_6_0", "-E", entry, "-Fo", str(work / "sm6.cso"), str(targets["hlsl_sm6"])])
    elif require_compilers:
        raise BuildError("dxc not found (Windows 10 SDK)")

    hashes = {}
    for key, path in targets.items():
        data = path.read_bytes().replace(b"\r\n", b"\n")
        path.write_bytes(data)
        hashes[key] = hashlib.sha256(data).hexdigest()
    (out_dir / "generated_manifest.json").write_text(
        json.dumps(
            {
                "artifacts": {k: str(ARTIFACTS[k].relative_to(ROOT)).replace("\\", "/") for k in targets},
                "sha256": hashes,
                "naga": run([naga, "--version"]).strip(),
                "fxc": bool(fxc),
                "dxc": bool(dxc),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    shutil.rmtree(work, ignore_errors=True)
    return hashes


def check(require_compilers: bool = False) -> list[str]:
    """Rebuild to a temp dir and report artifacts whose bytes differ from the committed ones."""
    tmp = Path(tempfile.mkdtemp(prefix="hogshade_check_"))
    try:
        fresh = build(tmp, require_compilers=require_compilers)
        stale = []
        for key, path in ARTIFACTS.items():
            committed = hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest() if path.exists() else None
            if committed != fresh[key]:
                stale.append(str(path.relative_to(ROOT)))
        return stale
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed artifacts are stale")
    parser.add_argument("--require-compilers", action="store_true", help="fail when fxc or dxc are missing")
    args = parser.parse_args(argv)
    try:
        if args.check:
            stale = check(require_compilers=args.require_compilers)
            if stale:
                print("stale generated artifacts:\n  " + "\n  ".join(stale))
                return 1
            print("generated artifacts are up to date")
            return 0
        hashes = build(HOSTS, require_compilers=args.require_compilers)
        for key, digest in hashes.items():
            print(f"{key:9s} {digest[:12]}  {ARTIFACTS[key].relative_to(ROOT)}")
        return 0
    except BuildError as e:
        print(f"build failed: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
