"""
HogShade: the gallery: check the picture manifest against its rules and generate Docs/gallery.md from it.
Package: tools/generate_gallery

    uv run tools/generate_gallery.py --check    # CI: the manifest obeys the rules and the page is current
    uv run tools/generate_gallery.py --write    # regenerate Docs/gallery.md

The manifest is verification/gallery.json: the pictures that matter, in sections by need, with pairs the
A/B page will consume later and grids (T3b, the owner's layout row): a matrix of listed pictures, rows by one
thing and columns by another (sets by hosts), rendered as a table GitHub shows side by side. The rules (PNG,
at most 1024 on a side, at most 1 MiB, fixed names overwritten in place, plain git) are the manifest's own
`rules` block and verification/README.md; a picture outside them is a finding here before it is a storage
problem.
"""

from __future__ import annotations

import argparse
import difflib
import json
import logging as _logging
import struct
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "verification" / "gallery.json"
PAGE = ROOT / "Docs" / "gallery.md"
HEADER = "<!-- generated by tools/generate_gallery.py --write from verification/gallery.json; do not edit -->"

_MODULE_NAME = "tools.generate_gallery"
__version__ = "0.1.0"
__updated__ = "2026-10-03"
_LOGGER = _logging.getLogger(_MODULE_NAME)

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_PICTURE_KEYS = ("path", "host", "feature", "caption", "made_by")


class GalleryError(ValueError):
    """The manifest cannot be used: malformed, or refused by ``--write`` with the findings in the message."""


@dataclass(frozen=True)
class Finding:
    """One rule broken, located for a human reading CI output."""

    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.where}: {self.message}"


def png_size(path: Path) -> tuple[int, int] | None:
    """Width and height from the PNG header, or ``None`` when the file is not a PNG."""
    with path.open("rb") as fh:
        head = fh.read(24)
    if len(head) < 24 or not head.startswith(_PNG_MAGIC) or head[12:16] != b"IHDR":
        return None
    width, height = struct.unpack(">II", head[16:24])
    return width, height


def load_manifest(path: Path = MANIFEST) -> dict:
    """The manifest as parsed JSON; a malformed file is a ``GalleryError`` naming the position."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise GalleryError(f"{path.name} is not valid JSON at line {e.lineno} column {e.colno}: {e.msg}") from e
    if not isinstance(data, dict):
        raise GalleryError(f"{path.name} must hold a JSON object at the top level, not {type(data).__name__}")
    return data


def check_manifest(manifest: dict, root: Path = ROOT) -> list[Finding]:
    """Every rule the manifest states, applied to every picture it names; empty when the gallery is sound."""
    out: list[Finding] = []
    where = "verification/gallery.json"
    for key in ("version", "rules", "hosts", "sections"):
        if key not in manifest:
            out.append(Finding(where, f"missing top-level field {key!r}"))
    if out:
        return out
    rules = manifest["rules"]
    if not isinstance(rules, dict) or not isinstance(manifest["sections"], list):
        return [Finding(where, "rules must be an object and sections a list")]
    if not isinstance(manifest.get("wanted", []), list):
        out.append(Finding(where, "wanted must be a list of strings"))
    if rules.get("format", "png") != "png":
        out.append(
            Finding(
                f"{where} rules", f"format must be 'png', the only format the rule allows, not {rules.get('format')!r}"
            )
        )
    limits: dict[str, int] = {}
    for key, default in (("max_side", 1024), ("max_bytes", 1 << 20)):
        value = rules.get(key, default)
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            out.append(Finding(f"{where} rules", f"{key} must be a positive integer, not {value!r}"))
            value = default
        limits[key] = value
    max_side, max_bytes = limits["max_side"], limits["max_bytes"]
    hosts = manifest["hosts"]
    if not isinstance(hosts, dict):
        return out + [Finding(where, "hosts must be an object of host id to description")]
    seen: set[str] = set()
    for s_index, section in enumerate(manifest["sections"]):
        s_where = f"{where} section {s_index}"
        if not isinstance(section, dict):
            out.append(Finding(s_where, f"must be an object, not {type(section).__name__}"))
            continue
        for key in ("title", "need", "pictures"):
            if not section.get(key):
                out.append(Finding(s_where, f"missing or empty {key!r}"))
        if not isinstance(section.get("pictures", []), list) or not isinstance(section.get("pairs", []), list):
            out.append(Finding(s_where, "pictures and pairs must be lists"))
            continue
        if not isinstance(section.get("grids", []), list):
            out.append(Finding(s_where, "grids must be a list"))
            continue
        for p_index, picture in enumerate(section.get("pictures", [])):
            if not isinstance(picture, dict):
                out.append(Finding(f"{s_where} picture {p_index}", f"must be an object, not {type(picture).__name__}"))
                continue
            p_where = f"{s_where} picture {picture.get('path')!r}"
            for key in _PICTURE_KEYS:
                if not isinstance(picture.get(key), str) or not picture.get(key):
                    out.append(Finding(p_where, f"missing or empty {key!r}"))
            rel = picture.get("path", "")
            if not isinstance(rel, str) or "\\" in rel or not rel.startswith("verification/") or ".." in rel.split("/"):
                out.append(Finding(p_where, "path must lie under verification/, forward slashes only, no '..'"))
                continue
            if rel in seen:
                out.append(Finding(p_where, "listed twice"))
            seen.add(rel)
            if picture.get("host") not in hosts:
                out.append(Finding(p_where, f"host {picture.get('host')!r} is not one of {sorted(hosts)}"))
            file = root / rel
            if not file.is_file():
                out.append(Finding(p_where, "no such file"))
                continue
            if not rel.endswith(".png"):
                out.append(Finding(p_where, f"the format is {rules.get('format', 'png')}"))
            size = png_size(file)
            if size is None:
                out.append(Finding(p_where, "not a PNG"))
            elif max(size) > max_side:
                out.append(Finding(p_where, f"{size[0]}x{size[1]} exceeds {max_side} on a side"))
            nbytes = file.stat().st_size
            if nbytes > max_bytes:
                out.append(Finding(p_where, f"{nbytes} bytes exceeds {max_bytes}"))
        for pair in section.get("pairs", []):
            if not isinstance(pair, dict):
                out.append(Finding(s_where, f"a pair must be an object, not {type(pair).__name__}"))
                continue
            pr_where = f"{s_where} pair {pair.get('left')!r} / {pair.get('right')!r}"
            for side in ("left", "right"):
                if pair.get(side) not in seen:
                    out.append(Finding(pr_where, f"{side} is not a picture listed above it"))
            if not pair.get("caption"):
                out.append(Finding(pr_where, "missing caption"))
        for g_index, grid in enumerate(section.get("grids", [])):
            out.extend(_check_grid(f"{s_where} grid {g_index}", grid, seen))
    return out


def _check_grid(where: str, grid: Any, seen: set[str]) -> list[Finding]:
    """A grid: a title and caption, columns as labels, rows each with a label and one cell per column, every cell a
    picture listed above it or null for an empty cell."""
    if not isinstance(grid, dict):
        return [Finding(where, f"a grid must be an object, not {type(grid).__name__}")]
    out: list[Finding] = []
    for key in ("title", "caption"):
        if not isinstance(grid.get(key), str) or not grid.get(key):
            out.append(Finding(where, f"missing or empty {key!r}"))
    columns = grid.get("columns")
    if not (isinstance(columns, list) and columns and all(isinstance(c, str) and c for c in columns)):
        return out + [Finding(where, "columns must be a non-empty list of labels")]
    rows = grid.get("rows")
    if not (isinstance(rows, list) and rows):
        return out + [Finding(where, "rows must be a non-empty list")]
    for r_index, row in enumerate(rows):
        r_where = f"{where} row {r_index}"
        if not isinstance(row, dict) or not isinstance(row.get("label"), str) or not row.get("label"):
            out.append(Finding(r_where, "a row is an object with a label and cells"))
            continue
        cells = row.get("cells")
        if not isinstance(cells, list) or len(cells) != len(columns):
            out.append(Finding(r_where, f"cells must list one entry per column ({len(columns)})"))
            continue
        for c_index, cell in enumerate(cells):
            if cell is not None and cell not in seen:
                out.append(Finding(f"{r_where} column {c_index}", f"{cell!r} is not a picture listed above it"))
    return out


def _counts(manifest: dict) -> tuple[int, int, int, int]:
    """Sections, pictures, pairs and wanted items, for the log."""
    raw = manifest.get("sections", [])
    sections = [s for s in raw if isinstance(s, dict)] if isinstance(raw, list) else []
    pictures = sum(len(s["pictures"]) for s in sections if isinstance(s.get("pictures"), list))
    pairs = sum(len(s["pairs"]) for s in sections if isinstance(s.get("pairs"), list))
    wanted = manifest.get("wanted", [])
    return len(sections), pictures, pairs, len(wanted) if isinstance(wanted, list) else 0


def _img(rel: str, alt: str) -> str:
    """A markdown image whose link resolves from ``Docs/``."""
    return f"![{alt}](../{rel})"


def render(manifest: dict) -> str:
    """The gallery page: one section per need, a table per picture set, pairs side by side, the wanted list."""
    out = [
        HEADER,
        "# Gallery",
        "",
        "**Status:** Living. Generated from `verification/gallery.json` by `tools/generate_gallery.py --write`;",
        "edit the manifest, not this page. The pictures are the latest capture of each fixed path under",
        "`verification/` (the rules in `verification/README.md`); a PR that changes a picture changes it here.",
        "",
        "| Host | What it is |",
        "| --- | --- |",
    ]
    for host, what in manifest["hosts"].items():
        out.append(f"| `{host}` | {what} |")
    out.append("")
    for section in manifest["sections"]:
        out += [f"## {section['title']}", "", section["need"], ""]
        for picture in section["pictures"]:
            out += [
                f"### {picture['feature']} (`{picture['host']}`)",
                "",
                _img(picture["path"], picture["feature"]),
                "",
                f"{picture['caption']}. Made by `{picture['made_by']}`; the file is `{picture['path']}`.",
                "",
            ]
        pairs = section.get("pairs", [])
        if pairs:
            out += ["### Side by side", "", "| Left | Right | Why |", "| --- | --- | --- |"]
            for pair in pairs:
                out.append(f"| {_img(pair['left'], 'left')} | {_img(pair['right'], 'right')} | {pair['caption']} |")
            out.append("")
        for grid in section.get("grids", []):
            columns = grid["columns"]
            out += [f"### {grid['title']}", "", grid["caption"], ""]
            out += ["| | " + " | ".join(columns) + " |", "| --- |" + " --- |" * len(columns)]
            for row in grid["rows"]:
                cells = [_img(c, f"{row['label']}, {columns[k]}") if c else "" for k, c in enumerate(row["cells"])]
                out.append(f"| **{row['label']}** | " + " | ".join(cells) + " |")
            out.append("")
    wanted = manifest.get("wanted", [])
    if wanted:
        out += ["## Wanted, not yet captured", ""]
        out += [f"- {item}" for item in wanted]
        out.append("")
    return "\n".join(out)


def check(root: Path = ROOT) -> tuple[list[Finding], str]:
    """The manifest's findings, and a unified diff when the committed page is stale (empty when current, or when
    there are findings: a manifest that breaks a rule is never rendered)."""
    manifest = load_manifest(root / "verification" / "gallery.json")
    _LOGGER.info(
        "checking %d sections, %d pictures, %d pairs, %d wanted from verification/gallery.json", *_counts(manifest)
    )
    findings = check_manifest(manifest, root)
    if findings:
        return findings, ""  # a manifest with findings is not rendered; the page cannot be judged against it
    fresh = render(manifest)
    page = root / "Docs" / "gallery.md"
    committed = page.read_text(encoding="utf-8") if page.exists() else ""
    diff = ""
    if committed != fresh:
        diff = "".join(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                fresh.splitlines(keepends=True),
                "Docs/gallery.md (committed)",
                "Docs/gallery.md (generated)",
            )
        )
    return findings, diff


def write(root: Path = ROOT) -> Path:
    """Regenerate ``Docs/gallery.md``; a manifest with findings is refused as a ``GalleryError``."""
    manifest = load_manifest(root / "verification" / "gallery.json")
    findings = check_manifest(manifest, root)
    if findings:
        raise GalleryError("the manifest has findings: " + "; ".join(str(f) for f in findings))
    page = root / "Docs" / "gallery.md"
    page.write_text(render(manifest), encoding="utf-8", newline="\n")
    _LOGGER.info("wrote %s: %d sections, %d pictures, %d pairs, %d wanted", page.name, *_counts(manifest))
    return page


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail when the manifest breaks a rule or the page is stale")
    mode.add_argument("--write", action="store_true", help="regenerate Docs/gallery.md from the manifest")
    args = parser.parse_args(argv)
    _logging.basicConfig(level=_logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    if args.write:
        try:
            write()
        except GalleryError as e:
            _LOGGER.error("%s", e)
            return 2
        return 0
    try:
        findings, diff = check()
    except GalleryError as e:
        _LOGGER.error("%s", e)
        return 1
    for f in findings:
        _LOGGER.error("%s", f)
    if diff:
        sys.stdout.write(diff)
        _LOGGER.error("Docs/gallery.md is stale; run tools/generate_gallery.py --write")
    if findings or diff:
        return 1
    _LOGGER.info("gallery check: every picture obeys the rules and Docs/gallery.md is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
