"""
HogShade: the gallery: check the picture manifest against its rules and generate Docs/gallery.md from it.
Package: tools/generate_gallery

    uv run tools/generate_gallery.py --check    # CI: the manifest obeys the rules and the page is current
    uv run tools/generate_gallery.py --write    # regenerate Docs/gallery.md

The manifest is verification/gallery.json: the pictures that matter, in sections by need, with pairs the
A/B page will consume later. The rules (PNG, at most 1024 on a side, at most 1 MiB, fixed names overwritten
in place, plain git) are the manifest's own `rules` block and verification/README.md; a picture outside them
is a finding here before it is a storage problem.
"""

from __future__ import annotations

import argparse
import difflib
import json
import logging as _logging
import struct
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "verification" / "gallery.json"
PAGE = ROOT / "Docs" / "gallery.md"
HEADER = "<!-- generated by tools/generate_gallery.py --write from verification/gallery.json; do not edit -->"

_MODULE_NAME = "tools.generate_gallery"
__version__ = "0.1.0"
__updated__ = "2026-10-03"
_LOGGER = _logging.getLogger(_MODULE_NAME)

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_PICTURE_KEYS = ("path", "host", "feature", "caption", "made_by")


@dataclass(frozen=True)
class Finding:
    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.where}: {self.message}"


def png_size(path: Path) -> tuple[int, int] | None:
    """Width and height from the PNG header, or ``None`` when the file is not a PNG."""
    with path.open("rb") as fh:
        head = fh.read(24)
    if len(head) < 24 or not head.startswith(_PNG_MAGIC) or head[12:16] != b"IHDR":
        return None
    width, height = struct.unpack(">II", head[16:24])
    return width, height


def load_manifest(path: Path = MANIFEST) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def check_manifest(manifest: dict, root: Path = ROOT) -> list[Finding]:
    """Every rule the manifest states, applied to every picture it names; empty when the gallery is sound."""
    out: list[Finding] = []
    where = "verification/gallery.json"
    for key in ("version", "rules", "hosts", "sections"):
        if key not in manifest:
            out.append(Finding(where, f"missing top-level field {key!r}"))
    if out:
        return out
    rules = manifest["rules"]
    max_side, max_bytes = int(rules.get("max_side", 1024)), int(rules.get("max_bytes", 1 << 20))
    hosts = manifest["hosts"]
    seen: set[str] = set()
    for s_index, section in enumerate(manifest["sections"]):
        s_where = f"{where} section {s_index}"
        for key in ("title", "need", "pictures"):
            if not section.get(key):
                out.append(Finding(s_where, f"missing or empty {key!r}"))
        for picture in section.get("pictures", []):
            p_where = f"{s_where} picture {picture.get('path')!r}"
            for key in _PICTURE_KEYS:
                if not isinstance(picture.get(key), str) or not picture.get(key):
                    out.append(Finding(p_where, f"missing or empty {key!r}"))
            rel = picture.get("path", "")
            if not isinstance(rel, str) or not rel.startswith("verification/") or ".." in rel.split("/"):
                out.append(Finding(p_where, "path is under verification/ with no '..'"))
                continue
            if rel in seen:
                out.append(Finding(p_where, "listed twice"))
            seen.add(rel)
            if picture.get("host") not in hosts:
                out.append(Finding(p_where, f"host {picture.get('host')!r} is not one of {sorted(hosts)}"))
            file = root / rel
            if not file.is_file():
                out.append(Finding(p_where, "no such file"))
                continue
            if not rel.endswith(".png"):
                out.append(Finding(p_where, f"the format is {rules.get('format', 'png')}"))
            size = png_size(file)
            if size is None:
                out.append(Finding(p_where, "not a PNG"))
            elif max(size) > max_side:
                out.append(Finding(p_where, f"{size[0]}x{size[1]} exceeds {max_side} on a side"))
            nbytes = file.stat().st_size
            if nbytes > max_bytes:
                out.append(Finding(p_where, f"{nbytes} bytes exceeds {max_bytes}"))
        for pair in section.get("pairs", []):
            pr_where = f"{s_where} pair {pair.get('left')!r} / {pair.get('right')!r}"
            for side in ("left", "right"):
                if pair.get(side) not in seen:
                    out.append(Finding(pr_where, f"{side} is not a picture listed above it"))
            if not pair.get("caption"):
                out.append(Finding(pr_where, "missing caption"))
    return out


def _img(rel: str, alt: str) -> str:
    return f"![{alt}](../{rel})"


def render(manifest: dict) -> str:
    """The gallery page: one section per need, a table per picture set, pairs side by side, the wanted list."""
    out = [
        HEADER,
        "# Gallery",
        "",
        "**Status:** Living. Generated from `verification/gallery.json` by `tools/generate_gallery.py --write`;",
        "edit the manifest, not this page. The pictures are the latest capture of each fixed path under",
        "`verification/` (the rules in `verification/README.md`); a PR that changes a picture changes it here.",
        "",
        "| Host | What it is |",
        "| --- | --- |",
    ]
    for host, what in manifest["hosts"].items():
        out.append(f"| `{host}` | {what} |")
    out.append("")
    for section in manifest["sections"]:
        out += [f"## {section['title']}", "", section["need"], ""]
        for picture in section["pictures"]:
            out += [
                f"### {picture['feature']} (`{picture['host']}`)",
                "",
                _img(picture["path"], picture["feature"]),
                "",
                f"{picture['caption']}. Made by `{picture['made_by']}`; the file is `{picture['path']}`.",
                "",
            ]
        pairs = section.get("pairs", [])
        if pairs:
            out += ["### Side by side", "", "| Left | Right | Why |", "| --- | --- | --- |"]
            for pair in pairs:
                out.append(f"| {_img(pair['left'], 'left')} | {_img(pair['right'], 'right')} | {pair['caption']} |")
            out.append("")
    wanted = manifest.get("wanted", [])
    if wanted:
        out += ["## Wanted, not yet captured", ""]
        out += [f"- {item}" for item in wanted]
        out.append("")
    return "\n".join(out)


def check(root: Path = ROOT) -> tuple[list[Finding], str]:
    """The manifest's findings and a unified diff when the committed page is stale (empty when current)."""
    manifest = load_manifest(root / "verification" / "gallery.json")
    findings = check_manifest(manifest, root)
    fresh = render(manifest)
    page = root / "Docs" / "gallery.md"
    committed = page.read_text(encoding="utf-8") if page.exists() else ""
    diff = ""
    if committed != fresh:
        diff = "".join(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                fresh.splitlines(keepends=True),
                "Docs/gallery.md (committed)",
                "Docs/gallery.md (generated)",
            )
        )
    return findings, diff


def write(root: Path = ROOT) -> Path:
    manifest = load_manifest(root / "verification" / "gallery.json")
    findings = check_manifest(manifest, root)
    if findings:
        raise ValueError("the manifest has findings: " + "; ".join(str(f) for f in findings))
    page = root / "Docs" / "gallery.md"
    page.write_text(render(manifest), encoding="utf-8", newline="\n")
    return page


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail when the manifest breaks a rule or the page is stale")
    mode.add_argument("--write", action="store_true", help="regenerate Docs/gallery.md from the manifest")
    args = parser.parse_args(argv)
    _logging.basicConfig(level=_logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    if args.write:
        try:
            page = write()
        except ValueError as e:
            _LOGGER.error("%s", e)
            return 2
        _LOGGER.info("wrote %s", page.relative_to(ROOT))
        return 0
    findings, diff = check()
    for f in findings:
        _LOGGER.error("%s", f)
    if diff:
        sys.stdout.write(diff)
        _LOGGER.error("Docs/gallery.md is stale; run tools/generate_gallery.py --write")
    if findings or diff:
        return 1
    _LOGGER.info("gallery check: the manifest obeys its rules and Docs/gallery.md is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
