"""
HogShade: the AI-first framework graph: validate the data and generate its page from it.
Package: tools/render_framework_graph

    uv run tools/render_framework_graph.py --check    # CI: the graph is well formed and the page is current
    uv run tools/render_framework_graph.py --write    # regenerate Docs/knowledge/ai-first-framework-graph.md

The data is Docs/knowledge/ai-first-framework.graph.json: nodes (a generic artifact, concept, rule, check or
ritual of an AI-first repository, in one of eight layers) and typed edges between them, drawn from a closed set
of relations. It names no project; its `seen` field says in which repositories a node exists today. The page
is a Mermaid overview, one Mermaid diagram per layer, and a table of every node, so GitHub draws it and a
reader or an agent can query it without a viewer.
"""

from __future__ import annotations

import argparse
import difflib
import json
import logging as _logging
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

_MODULE_NAME = "tools.render_framework_graph"
__version__ = "0.1.2"
__updated__ = "2026-10-08"
_LOGGER = _logging.getLogger(_MODULE_NAME)

ROOT = Path(__file__).resolve().parents[1]
_KNOWLEDGE = Path("Docs") / "knowledge"
DATA = ROOT / _KNOWLEDGE / "ai-first-framework.graph.json"
PAGE = ROOT / _KNOWLEDGE / "ai-first-framework-graph.md"
HEADER = "<!-- generated by tools/render_framework_graph.py --write from ai-first-framework.graph.json; do not edit -->"

_ID_RE = re.compile(r"[a-z][a-z0-9]*(-[a-z0-9]+)*")
_LAYER_RE = re.compile(r"[a-z][a-z0-9]*")
_RESERVED = frozenset({"end", "graph", "subgraph", "class", "style", "click", "default", "flowchart"})
_SEEN_LETTERS = "HLS"
_NODE_KEYS = ("id", "kind", "layer", "label", "seen", "summary")
_SHAPES = {
    "artifact": ("[", "]"),
    "concept": ("(", ")"),
    "rule": ("{{", "}}"),
    "check": ("[[", "]]"),
    "ritual": ("([", "])"),
}
_STYLE = {
    "artifact": "fill:#e8f0fe,stroke:#4a6fa5",
    "concept": "fill:#f3f3f3,stroke:#888",
    "rule": "fill:#fff4d6,stroke:#b8860b",
    "check": "fill:#e3f6e3,stroke:#3a7d3a",
    "ritual": "fill:#fde8f0,stroke:#a5476b",
}
_ARROWS = {
    "links-to": "-->",
    "reads": "-.->",
    "records": "-->",
    "feeds": "==>",
    "gates": "==>",
    "enforces": "-->",
    "mechanises": "==>",
    "constrains": "-.->",
    "defines": "-->",
    "annotates": "-.->",
}


_STATUS_LINE = (
    "**Status:** Living. Generated from `ai-first-framework.graph.json` by "
    "`tools/render_framework_graph.py --write`; edit the data, not this page. "
    "The description is [ai-first-framework.md](ai-first-framework.md)."
)
_SEEN_LINE = (
    "Nothing here names a project. *Seen in* says where a concept exists today: "
    "**H** HogShade, **L** LargeWorlds, **S** SpriteJammer."
)
_READING = (
    "Shapes say what a node is: a rectangle is an artifact (a file or directory), a rounded box a concept, "
    "a hexagon a rule, a double-bordered box a check (it goes red), a stadium a ritual. Arrows say how: a thick "
    "arrow is a flow that must happen (`feeds`, `gates`, `mechanises`), a plain arrow is a reference or a record, "
    "a dotted arrow a constraint or an annotation. Every edge is labelled with its relation."
)
_BETWEEN = "Edge counts between layers; edges inside one layer are in the layer's own diagram below."


class GraphError(Exception):
    """The data file cannot be read or is not the shape this tool expects."""


def load(path: Path = DATA) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise GraphError(f"cannot read {path}: {e}") from e
    if not isinstance(data, dict):
        raise GraphError(f"{path} is not a JSON object")
    return data


def _text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _shape_problems(data: dict[str, Any]) -> list[str]:
    """The top-level shape: dicts where dicts belong, lists of objects, closed sets the renderer can draw."""
    found = [
        f"missing top-level key '{k}'" for k in ("layers", "kinds", "relations", "nodes", "edges") if k not in data
    ]
    if found:
        return found
    for key in ("layers", "kinds", "relations"):
        value = data[key]
        if not isinstance(value, dict) or not all(_text(k) and _text(v) for k, v in value.items()):
            found.append(f"'{key}' must be an object of non-empty strings")
    for key in ("nodes", "edges"):
        value = data[key]
        if not isinstance(value, list) or not all(isinstance(x, dict) for x in value):
            found.append(f"'{key}' must be a list of objects")
    if found:
        return found
    found += [f"kind '{k}' has no shape in the renderer" for k in data["kinds"] if k not in _SHAPES]
    found += [f"relation '{r}' has no arrow in the renderer" for r in data["relations"] if r not in _ARROWS]
    for layer in data["layers"]:
        if not _LAYER_RE.fullmatch(layer) or layer in _RESERVED:
            found.append(f"layer '{layer}' is not a plain lower-case word the diagrams can use as an id")
    return found


def problems(data: Any) -> list[str]:
    """Every way the data breaks its own contract; an empty list is a well-formed graph."""
    if not isinstance(data, dict):
        return ["the data is not a JSON object"]
    found = _shape_problems(data)
    if found:
        return found
    layers, kinds, relations = data["layers"], data["kinds"], data["relations"]
    ids: set[str] = set()
    for n in data["nodes"]:
        missing = [k for k in _NODE_KEYS if not _text(n.get(k))]
        if missing:
            found.append(f"node {n.get('id', '?')}: missing or not text: {', '.join(missing)}")
            continue
        nid = n["id"]
        if not _ID_RE.fullmatch(nid):
            found.append(f"node id '{nid}' is not lower-case kebab-case")
        elif _mid(nid) in _RESERVED:
            found.append(f"node id '{nid}' is a Mermaid keyword")
        if nid in ids:
            found.append(f"duplicate node id '{nid}'")
        ids.add(nid)
        if n["kind"] not in kinds:
            found.append(f"node {nid}: unknown kind '{n['kind']}'")
        if n["layer"] not in layers:
            found.append(f"node {nid}: unknown layer '{n['layer']}'")
        if any(c not in _SEEN_LETTERS for c in n["seen"]) or len(set(n["seen"])) != len(n["seen"]):
            found.append(f"node {nid}: seen '{n['seen']}' must be distinct letters of {_SEEN_LETTERS}")
    seen_edges: set[tuple[str, str, str]] = set()
    touched: set[str] = set()
    for e in data["edges"]:
        a, b, rel = e.get("from"), e.get("to"), e.get("relation")
        if not (_text(a) and _text(b) and _text(rel)):
            found.append(f"edge {a!r} -> {b!r}: from, to and relation must each be text")
            continue
        if a not in ids or b not in ids:
            found.append(f"edge {a} -> {b}: an endpoint is not a node")
            continue
        if a == b:
            found.append(f"edge {a} -> {b}: a node points at itself")
        if rel not in relations:
            found.append(f"edge {a} -> {b}: unknown relation '{rel}'")
        if (a, b, rel) in seen_edges:
            found.append(f"duplicate edge {a} -[{rel}]-> {b}")
        seen_edges.add((a, b, rel))
        touched.update((a, b))
    for orphan in sorted(ids - touched):
        found.append(f"node {orphan} has no edge")
    for rel in sorted(set(relations) - {e["relation"] for e in data["edges"] if _text(e.get("relation"))}):
        found.append(f"relation '{rel}' is declared and never used")
    used_layers = {n.get("layer") for n in data["nodes"]}
    for layer in layers:
        if layer not in used_layers:
            found.append(f"layer '{layer}' has no node")
    return found


def _mid(nid: str) -> str:
    """A Mermaid-safe identifier (kebab-case is not)."""
    return nid.replace("-", "_")


def _label(text: str) -> str:
    return '"' + text.replace('"', "'") + '"'


def _node_line(n: dict[str, Any], indent: str) -> str:
    left, right = _SHAPES[n["kind"]]
    return f"{indent}{_mid(n['id'])}{left}{_label(n['label'])}{right}"


def _flowchart(nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> str:
    """One Mermaid flowchart: every node given, every edge among them."""
    keep = {n["id"] for n in nodes}
    lines = ["```mermaid", "flowchart LR"]
    lines.extend(_node_line(n, "  ") for n in nodes)
    for e in edges:
        if e["from"] in keep and e["to"] in keep:
            arrow = _ARROWS[e["relation"]]
            lines.append(f"  {_mid(e['from'])} {arrow}|{e['relation']}| {_mid(e['to'])}")
    for kind, style in _STYLE.items():
        ids = [_mid(n["id"]) for n in nodes if n["kind"] == kind]
        if ids:
            lines.append(f"  classDef {kind} {style}")
            lines.append(f"  class {','.join(ids)} {kind}")
    lines.append("```")
    return "\n".join(lines)


def render(data: dict[str, Any]) -> str:
    nodes, edges = data["nodes"], data["edges"]
    by_id = {n["id"]: n for n in nodes}
    layers = data["layers"]
    out = [
        HEADER,
        "# The AI-first framework graph",
        "",
        _STATUS_LINE,
        "",
        f"{len(nodes)} concepts in {len(layers)} layers, joined by {len(edges)} typed edges. {_SEEN_LINE}",
        "",
        "## Reading the diagrams",
        "",
        _READING,
        "",
        "| Relation | Meaning |",
        "| --- | --- |",
    ]
    counts = Counter(e["relation"] for e in edges)
    out.extend(f"| `{r}` | {m} ({counts[r]}) |" for r, m in data["relations"].items())
    out += ["", "## The layers", ""]
    cross = Counter((by_id[e["from"]]["layer"], by_id[e["to"]]["layer"]) for e in edges)
    lines = ["```mermaid", "flowchart TB"]
    for layer, title in layers.items():
        size = sum(1 for n in nodes if n["layer"] == layer)
        lines.append(f"  {layer}[{_label(f'{layer} ({size}): {title}')}]")
    for (a, b), c in sorted(cross.items()):
        if a != b:
            lines.append(f"  {a} -->|{c}| {b}")
    lines.append("```")
    out += [
        "\n".join(lines),
        "",
        _BETWEEN,
        "",
    ]
    for layer, title in layers.items():
        members = [n for n in nodes if n["layer"] == layer]
        out += [f"## {layer.capitalize()}: {title}", ""]
        own = {m["id"] for m in members}
        touching = [e for e in edges if e["from"] in own or e["to"] in own]
        wanted = own | {e["from"] for e in touching} | {e["to"] for e in touching}
        out += [_flowchart([n for n in nodes if n["id"] in wanted], touching), ""]
        out += ["| Concept | Kind | Seen in | What it is |", "| --- | --- | --- | --- |"]
        for n in members:
            out.append(f"| **{n['label']}** (`{n['id']}`) | {n['kind']} | {n['seen']} | {n['summary']} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def check(root: Path = ROOT) -> tuple[list[str], str]:
    """The data's problems, and a diff of the committed page against a fresh render (empty when current)."""
    data = load(root / _KNOWLEDGE / DATA.name)
    found = problems(data)
    if found:
        return found, ""
    page = root / _KNOWLEDGE / PAGE.name
    try:
        have = page.read_text(encoding="utf-8").replace("\r\n", "\n") if page.exists() else ""
    except (OSError, ValueError) as e:
        raise GraphError(f"cannot read {page}: {e}") from e
    want = render(data)
    if have == want:
        return [], ""
    return [], "".join(difflib.unified_diff(have.splitlines(True), want.splitlines(True), "committed", "rendered", n=1))


def write(root: Path = ROOT) -> Path:
    data = load(root / _KNOWLEDGE / DATA.name)
    found = problems(data)
    if found:
        raise GraphError("the graph has problems: " + "; ".join(found))
    page = root / _KNOWLEDGE / PAGE.name
    page.write_text(render(data), encoding="utf-8", newline="\n")
    _LOGGER.info(f"wrote {page.name}: {len(data['nodes'])} nodes, {len(data['edges'])} edges")
    return page


def main(argv: list[str] | None = None, root: Path = ROOT) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail when the graph is malformed or the page is stale")
    mode.add_argument("--write", action="store_true", help="regenerate the page from the data")
    args = parser.parse_args(argv)
    _logging.basicConfig(level=_logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    try:
        if args.write:
            write(root)
            return 0
        found, diff = check(root)
    except GraphError as e:
        _LOGGER.error(str(e))
        return 2 if args.write else 1
    for f in found:
        _LOGGER.error(f)
    if diff:
        sys.stdout.write(diff)
        _LOGGER.error("the graph page is stale; run tools/render_framework_graph.py --write")
    if found or diff:
        return 1
    _LOGGER.info("framework graph check: the graph is well formed and its page is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
